import { Artist, ArtworkWithArtist, Event, Business } from './types';

export const mockArtists: Artist[] = [
  {
    id: '1',
    user_id: 'user-1',
    name: 'Mary Molefe',
    slug: 'mary-molefe',
    bio: 'A contemporary painter from Gaborone, known for her vibrant abstract works that explore the connection between nature and urban life in Botswana.',
    profile_image: 'https://picsum.photos/seed/artist1/400/400',
    phone: '26771234567',
    email: 'mary.molefe@example.com',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'user-2',
    name: 'John Doe',
    slug: 'john-doe',
    bio: 'A sculptor who works with recycled materials to create thought-provoking pieces about consumerism and the environment. His work is both playful and profound.',
    profile_image: 'https://picsum.photos/seed/artist2/400/400',
    phone: '26772345678',
    email: 'john.doe@example.com',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'user-3',
    name: 'Jane Smith',
    slug: 'jane-smith',
    bio: 'A photographer capturing the serene landscapes and intimate portraits of rural Botswana. Her black and white photos tell stories of tradition and change.',
    profile_image: 'https://picsum.photos/seed/artist3/400/400',
    phone: '26773456789',
    email: 'jane.smith@example.com',
    created_at: new Date().toISOString(),
  },
];

export const mockArtworks: ArtworkWithArtist[] = [
  {
    id: '1',
    artist_id: '1',
    title: 'Kalahari Sunset',
    description: 'An abstract representation of a Kalahari sunset, using bold colors and textures to evoke the heat and beauty of the desert.',
    price: 15000,
    image_url: 'https://picsum.photos/seed/artwork1/800/800',
    category: 'Painting',
    status: 'available',
    created_at: new Date().toISOString(),
    artists: {
      name: 'Mary Molefe',
      slug: 'mary-molefe',
      phone: '26771234567',
      profile_image: 'https://picsum.photos/seed/artist1/400/400',
      bio: 'A contemporary painter from Gaborone, known for her vibrant abstract works that explore the connection between nature and urban life in Botswana.'
    },
  },
  {
    id: '2',
    artist_id: '2',
    title: 'Urban Relic',
    description: 'A sculpture made from discarded electronics and metal scraps, shaped into a futuristic totem. It questions what we value and what we throw away.',
    price: 25000,
    image_url: 'https://picsum.photos/seed/artwork2/800/800',
    category: 'Sculpture',
    status: 'available',
    created_at: new Date().toISOString(),
    artists: {
      name: 'John Doe',
      slug: 'john-doe',
      phone: '26772345678',
      profile_image: 'https://picsum.photos/seed/artist2/400/400',
      bio: 'A sculptor who works with recycled materials to create thought-provoking pieces about consumerism and the environment. His work is both playful and profound.'
    },
  },
  {
    id: '3',
    artist_id: '3',
    title: 'Elder\'s Wisdom',
    description: 'A powerful black and white portrait of a village elder, capturing the lines of a life well-lived and the depth of his gaze.',
    price: 8000,
    image_url: 'https://picsum.photos/seed/artwork3/800/800',
    category: 'Photography',
    status: 'sold',
    created_at: new Date().toISOString(),
    artists: {
      name: 'Jane Smith',
      slug: 'jane-smith',
      phone: '26773456789',
      profile_image: 'https://picsum.photos/seed/artist3/400/400',
      bio: 'A photographer capturing the serene landscapes and intimate portraits of rural Botswana. Her black and white photos tell stories of tradition and change.'
    },
  },
  {
    id: '4',
    artist_id: '1',
    title: 'Okavango Dreams',
    description: 'A mixed-media piece incorporating sand and reeds, this artwork is a dreamy, textured depiction of the Okavango Delta at dawn.',
    price: 18000,
    image_url: 'https://picsum.photos/seed/artwork4/800/800',
    category: 'Mixed Media',
    status: 'available',
    created_at: new Date().toISOString(),
    artists: {
      name: 'Mary Molefe',
      slug: 'mary-molefe',
      phone: '26771234567',
      profile_image: 'https://picsum.photos/seed/artist1/400/400',
      bio: 'A contemporary painter from Gaborone, known for her vibrant abstract works that explore the connection between nature and urban life in Botswana.'
    },
  },
  {
    id: '5',
    artist_id: '2',
    title: 'Plastic Kingdom',
    description: 'A whimsical castle built entirely from colorful plastic bottle caps, a commentary on the pervasiveness of plastic waste in our world.',
    price: 22000,
    image_url: 'https://picsum.photos/seed/artwork5/800/800',
    category: 'Sculpture',
    status: 'reserved',
    created_at: new Date().toISOString(),
    artists: {
      name: 'John Doe',
      slug: 'john-doe',
      phone: '26772345678',
      profile_image: 'https://picsum.photos/seed/artist2/400/400',
      bio: 'A sculptor who works with recycled materials to create thought-provoking pieces about consumerism and the environment. His work is both playful and profound.'
    },
  },
  {
    id: '6',
    artist_id: '1',
    title: 'Gaborone Nightlife',
    description: 'The energy and movement of the city at night are captured in this dynamic painting, with streaks of light and deep shadows.',
    price: 16500,
    image_url: 'https://picsum.photos/seed/artwork6/800/800',
    category: 'Painting',
    status: 'available',
    created_at: new Date().toISOString(),
    artists: {
      name: 'Mary Molefe',
      slug: 'mary-molefe',
      phone: '26771234567',
      profile_image: 'https://picsum.photos/seed/artist1/400/400',
      bio: 'A contemporary painter from Gaborone, known for her vibrant abstract works that explore the connection between nature and urban life in Botswana.'
    },
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Annual Artists Workshop',
    description: 'A week-long intensive workshop for emerging artists, focusing on new techniques and professional development.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    location: 'Thapong Visual Art Centre',
    image_url: 'https://picsum.photos/seed/event1/1200/800',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Contemporary Sculpture Exhibition Opening',
    description: 'Join us for the opening night of a new exhibition showcasing the best of contemporary sculpture from across Botswana.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    location: 'Main Gallery, Thapong',
    image_url: 'https://picsum.photos/seed/event2/1200/800',
    created_at: new Date().toISOString(),
  },
   {
    id: '3',
    title: 'Art in the Park Festival',
    description: 'A family-friendly day of art, music, and food in the park. Featuring live painting, craft stalls, and childrens activities.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 60)).toISOString(),
    location: 'Gaborone National Park',
    image_url: 'https://picsum.photos/seed/event3/1200/800',
    created_at: new Date().toISOString(),
  },
];

export const mockBusinesses: Business[] = [
    {
        id: '1',
        name: 'The Artisan Cafe',
        slug: 'the-artisan-cafe',
        description: 'A cozy cafe within the art centre, serving locally sourced coffee, light meals, and homemade cakes. The perfect spot to relax and get inspired.',
        phone: '267 311 1111',
        whatsapp: '26774111111',
        image_url: 'https://picsum.photos/seed/business1/800/600',
        opening_hours: 'Mon-Fri: 8am-5pm, Sat: 9am-2pm',
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Creative Supplies Co.',
        slug: 'creative-supplies-co',
        description: 'Your one-stop shop for high-quality art supplies. From canvases and paints to sketchbooks and brushes, we have everything an artist needs.',
        phone: '267 322 2222',
        whatsapp: '26774222222',
        image_url: 'https://picsum.photos/seed/business2/800/600',
        opening_hours: 'Mon-Sat: 9am-6pm',
        created_at: new Date().toISOString(),
    },
     {
        id: '3',
        name: 'Framing Focus',
        slug: 'framing-focus',
        description: 'Professional custom framing services to give your artwork the perfect finish. We offer a wide range of styles and expert advice.',
        phone: '267 333 3333',
        whatsapp: '26774333333',
        image_url: 'https://picsum.photos/seed/business3/800/600',
        opening_hours: 'Mon-Fri: 9am-5pm',
        created_at: new Date().toISOString(),
    },
];
